DROP TABLE COMMANDS;
DROP TABLE PAYMENTS_METHODS;
DROP TABLE PRODUCTS;
DROP TABLE PRODUCT_COMMAND;
DROP TABLE STOCK;
DROP TABLE STOCK_PRODUCT;
DROP TABLE SUPPLIERS;
DROP TABLE SUPPLIER_STOCK;
DROP TABLE SUPPLIER_STOCK_OFFER;
DROP TABLE NOTIFICATION_STOCK;
DROP TABLE DATABASECHANGELOG;
DROP TABLE DATABASECHANGELOGLOCK;


DROP SEQUENCE COMMANDS_SEQ;
DROP SEQUENCE PAYMENTS_METHODS_SEQ;
DROP SEQUENCE PRODUCTS_SEQ;
DROP SEQUENCE PRODUCT_COMMAND_SEQ;
DROP SEQUENCE STOCK_PRODUCT_SEQ;
DROP SEQUENCE STOCK_SEQ;
DROP SEQUENCE SUPPLIERS_SEQ;
DROP SEQUENCE SUPPLIER_STOCK_OFFER_SEQ;
DROP SEQUENCE SUPPLIER_STOCK_SEQ;