-- TABLES
-- Table: COMMANDS
CREATE TABLE COMMANDS (
    COMMAND_ID INTEGER  NOT NULL,
    COMMAND_NUMBER INTEGER   NULL,
    COMMAND_VALUE NUMBER(10,2) NOT NULL,
    DATETIME_COMMAND TIMESTAMP,
    CONSTRAINT COMMANDS_PK PRIMARY KEY (COMMAND_ID)
) ;

-- Table: PRODUCTS
CREATE TABLE PRODUCTS (
    PRODUCT_ID INTEGER  NULL,
    PRODUCT_NAME VARCHAR2(255)   NULL,
    PRODUCT_VALUE NUMBER(10,2)   NULL,
    PRODUCT_TYPE VARCHAR2(50)   NULL,
    CONSTRAINT PRODUCTS_PK PRIMARY KEY (PRODUCT_ID)
) ;

-- Table: PRODUCT_COMMAND
CREATE TABLE PRODUCT_COMMAND (
    PRODUCT_DEMAND_ID INTEGER  NOT NULL,
    PC_QUANTITY NUMBER(10,2)  NULL,
    PC_DATETIME_ORDER DATE  NULL,
    PRODUCT_ID INTEGER   NULL,
    COMMAND_ID INTEGER   NULL,
    PC_MEASUREMENT VARCHAR(2) NULL,
    CONSTRAINT PRODUCT_COMMAND_PK PRIMARY KEY (PRODUCT_DEMAND_ID)
) ;


-- FOREIGN KEYS

ALTER TABLE PRODUCT_COMMAND
ADD CONSTRAINT FK_PRODUCT_COMMAND_COMMANDS
FOREIGN KEY (COMMAND_ID)
REFERENCES COMMANDS(COMMAND_ID);

-- Adicione a chave estrangeira na tabela PRODUCT_COMMAND para relacioná-la com a tabela PRODUCTS
ALTER TABLE PRODUCT_COMMAND
ADD CONSTRAINT FK_PRODUCT_COMMAND_PRODUCTS
FOREIGN KEY (PRODUCT_ID)
REFERENCES PRODUCTS(PRODUCT_ID);

-- SEQUENCES
-- Sequence: COMMANDS_SEQ
CREATE SEQUENCE COMMANDS_SEQ
      INCREMENT BY 1
      NOMINVALUE
      NOMAXVALUE
      START WITH 1
      NOCACHE
      NOCYCLE;


-- Sequence: PRODUCT_COMMAND_SEQ
CREATE SEQUENCE PRODUCT_COMMAND_SEQ
      INCREMENT BY 1
      NOMINVALUE
      NOMAXVALUE
      START WITH 1
      NOCACHE
      NOCYCLE;

-- Sequence: PRODUCTS_SEQ
CREATE SEQUENCE PRODUCTS_SEQ
      INCREMENT BY 1
      NOMINVALUE
      NOMAXVALUE
      START WITH 1
      NOCACHE
      NOCYCLE;


-- Trigger de id

-- Trigger para a sequence Commands_seq
CREATE OR REPLACE EDITIONABLE TRIGGER "ADMIN"."TRG_SEQ_COMMAND_ID"
 BEFORE INSERT ON "COMMANDS" 
 FOR EACH ROW 
 BEGIN 
   SELECT COMMANDS_SEQ.NEXTVAL 
   INTO :new.COMMAND_ID 
   FROM dual; 
 END; 
 / 
 ALTER TRIGGER "ADMIN"."TRG_SEQ_COMMAND_ID" ENABLE;

-- Trigger para a sequence PRODUCT_COMMAND_SEQ
CREATE OR REPLACE EDITIONABLE TRIGGER "ADMIN"."TRG_SEQ_PRODUCT_DEMAND_ID"
 BEFORE INSERT ON "PRODUCT_COMMAND" 
 FOR EACH ROW 
 BEGIN 
   SELECT PRODUCT_COMMAND_SEQ.NEXTVAL 
   INTO :new.PRODUCT_DEMAND_ID 
   FROM dual; 
 END; 
 / 
 ALTER TRIGGER "ADMIN"."TRG_SEQ_PRODUCT_DEMAND_ID" ENABLE;

-- Trigger para a sequence PRODUCTS_SEQ
CREATE OR REPLACE EDITIONABLE TRIGGER "ADMIN"."TRG_SEQ_PRODUCT_ID"
 BEFORE INSERT ON "PRODUCTS" 
 FOR EACH ROW 
 BEGIN 
   SELECT PRODUCTS_SEQ.NEXTVAL 
   INTO :new.PRODUCT_ID 
   FROM dual; 
 END; 
 / 
 ALTER TRIGGER "ADMIN"."TRG_SEQ_PRODUCT_ID" ENABLE;
