-- SEQUENCES
-- Sequence: COMMANDS_SEQ
CREATE SEQUENCE COMMANDS_SEQ
      INCREMENT BY 1
      NOMINVALUE
      NOMAXVALUE
      START WITH 1
      NOCACHE
      NOCYCLE;


-- Sequence: PRODUCT_COMMAND_SEQ
CREATE SEQUENCE PRODUCT_COMMAND_SEQ
      INCREMENT BY 1
      NOMINVALUE
      NOMAXVALUE
      START WITH 1
      NOCACHE
      NOCYCLE;

-- Sequence: PRODUCTS_SEQ
CREATE SEQUENCE PRODUCTS_SEQ
      INCREMENT BY 1
      NOMINVALUE
      NOMAXVALUE
      START WITH 1
      NOCACHE
      NOCYCLE;
